site_name: Sushant Gnawali
site_dir : docs/
docs_dir: src/
site_url: https://sushantgnawali.com.np
nav:
  - Introduction: index.md
markdown_extensions:
  - attr_list
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
